name: Publish johnnydev
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/johnny-mh/johnny-mh.github.io.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx nx affected --target=publish --parallel=3
