name: Publish johnnydev
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm

      - run: git remote set-url origin https://git:${SECRET_TOKEN}@github.com/johnny-mh/johnny-mh.github.io.git
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

      - name: Build
        run: NODE_ENV=production pnpm turbo build --filter astro-blog

      - name: Publish
        run: pnpm gh-pages -f -t -d apps/astro-blog/dist -b master -u 'github-actions-bot <support+actions@github.com>'
