name: Publish johnnydev
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - run: git remote set-url origin https://git:${SECRET_TOKEN}@github.com/johnny-mh/johnny-mh.github.io.git
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

      - run: NODE_ENV=production yarn turbo build --filter astro-blog

      - run: yarn gh-pages -f -d apps/astro-blog/dist -b master -u 'github-actions-bot <support+actions@github.com>'
